name: GitHub Actions Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

# on: 
#   schedule:
#     - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"


on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Install R on ubuntu runner
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'

      - name: Run r script
        run: | 
          Rscript write_rds.R

      - name: Commit and push rds to repo
        run: |
          git config --global user.name "leahyc-parliament"
          git config --global user.email "leahyc@parliament.uk"
          git add .
          git commit -m "Add generated RDS file [skip ci]" || echo "No changes to commit"
          git push
